[project]
name = "neural-networks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.6",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
